#!/bin/sh

readonly PRIMARY="DP-0"
readonly RESOLUTION="1920x1080"

xrandr \
    --output "${PRIMARY}" --primary --mode "${RESOLUTION}" -r 60 --pos 0x0 --rotate normal \
    --output HDMI-0 --mode "${RESOLUTION}" -r 60 --right-of "${PRIMARY}" --rotate normal \
    --output DP-1 --off \
    --output DVI-D-0 --off
