#!/usr/bin/env zsh

zfiles=(
    ~/.zshenv
)

zfiles+=($(find "${ZDOTDIR}/" -maxdepth 1 -type f -not -name '*.zwc'))

for zfile in "${zfiles[@]}"
do
    echo "zcompile ${zfile}"
    zcompile "${zfile}"
done