# vim: ft=swayconfig
# Sway bar

bar {
    mode dock
    position bottom
    status_command i3blocks
    wrap_scroll no
    bindsym button4 nop
    bindsym button5 nop
    hidden_state hide
    output *
    tray_output $primary
    strip_workspace_name no
    strip_workspace_numbers no
    modifier $mod
}

exec ~/.config/i3blocks/scripts/layout_change_handler.sh
