#!/usr/bin/env bash

set -x

declare RND="${RANDOM}"
declare SESSION="sandbox${RND}"

while tmux has-session -t "${SESSION}" 2>/dev/null
do
    RND="${RANDOM}"
    SESSION="sandbox${RND}"
done

readonly RND
readonly SESSION


declare WORKING_PROJECT
WORKING_PROJECT="$(mktemp -td "sandbox${RND}.XXXX")"
readonly WORKING_PROJECT

tmux new-session -s "${SESSION}" -d -c "${WORKING_PROJECT}"
tmux switch-client -t "${SESSION}"