#!/bin/sh

loginctl enable-linger "${USER}"
command -v systemctl >/dev/null && systemctl --user enable --now tmux
git clone https://github.com/tmux-plugins/tpm "${HOME}/.config/tmux/plugins/tpm" | true
