
local status, telescope = pcall(require, "telescope")
if (not status) then return end

telescope.load_extension('fzf')

telescope.setup {
    defaults = {
     selection_caret = " ",
     path_display = { "smart" },
     file_ignore_patterns = {
       ".git/",
       "target/",
       "docs/",
       "vendor/*",
       "%.lock",
       "pycache/*",
       "%.sqlite3",
       "%.ipynb",
       "node_modules/*",
       "%.svg",
       "%.otf",
       "%.ttf",
       "%.webp",
       ".dart_tool/",
       ".github/",
       ".gradle/",
       ".idea/",
       ".settings/",
       ".vscode/",
       "pycache/",
       "build/",
       "env/",
       "gradle/",
       "node_modules/",
       "%.pdb",
       "%.dll",
       "%.class",
       "%.exe",
       "%.cache",
       "%.ico",
       "%.pdf",
       "%.dylib",
       "%.jar",
       "%.docx",
       "%.met",
       "smalljre_*/*",
       ".vale/",
       "%.burp",
       "%.mp4",
       "%.mkv",
       "%.rar",
       "%.zip",
       "%.7z",
       "%.tar",
       "%.bz2",
       "%.epub",
       "%.flac",
       "%.tar.gz",
     },
    }
}
