#!/bin/sh
set -eu

prefix="${HOME}/Games"
mkdir "${prefix}" || true

cd "${prefix}"
wget -c -O "${prefix}/starsector.zip" "https://f005.backblazeb2.com/file/fractalsoftworks/release/starsector_linux-0.98a-RC8.zip"
unzip "${prefix}/starsector.zip"


wget -c -O "${prefix}/starsector-rusificator.zip" "https://paste.thek4n.ru/lvsaHLOAmFfqnv/"
unzip -o "${prefix}/starsector-rusificator.zip"


cd "${prefix}/starsector/mods/"
wget -c -O "${prefix}/starsector/mods/Unthemed Weapons Collection.zip" "https://paste.thek4n.ru/pGbkhFFgGcSysm/"
unzip "${prefix}/starsector/mods/Unthemed Weapons Collection.zip"
