#!/bin/sh
set -e
if command -v makepkg >/dev/null && [ -e PKGBUILD ]; then
    if [ -e VERSION ]; then
        sed -i "s/pkgver=.\+/pkgver=$(cat VERSION)/" PKGBUILD
        git add PKGBUILD
    fi

    makepkg --printsrcinfo > .SRCINFO
    git add .SRCINFO
    exit
fi
