#!/bin/bash

if [[ "$1" == "docker-cli-plugin-metadata" ]]; then
cat << HERE
{
     "SchemaVersion": "0.1.0",
     "Vendor": "example.com",
     "Version": "v0.1.0",
     "ShortDescription": "Bash based Docker cli-plugin"
}
HERE
exit
fi

result="CONTAINER NAME;IMAGE;IP\n"

for container in $(docker ps -q | tr '\n' ' ')
do
    IP="$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$container" 2>/dev/null)"
    container_name="$(docker inspect --format='{{.Name}}' "$container" 2>/dev/null)"
    image_name="$(docker inspect --format='{{.Config.Image}}' "$container" 2>/dev/null)"
    result+="${container_name#"/"};$image_name;$IP\n"
done

echo -e $result 2>/dev/null | column -t -s ";"
